// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transcription.DAL;

#nullable disable

namespace Transcription.DAL.Migrations
{
    [DbContext(typeof(WbContext))]
    [Migration("20221128092521_AddUserInfo")]
    partial class AddUserInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transcription.DAL.Models.ChatState", b =>
                {
                    b.Property<long>("ChatStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("UserChatId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatStateId");

                    b.HasIndex("ChatStateId")
                        .IsUnique();

                    b.ToTable("ChatStates");
                });

            modelBuilder.Entity("Transcription.DAL.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Transcription.DAL.Models.YandexRequest", b =>
                {
                    b.Property<string>("YandexRequestId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserChatId")
                        .HasColumnType("bigint");

                    b.HasKey("YandexRequestId");

                    b.ToTable("YandexRequests");
                });

            modelBuilder.Entity("Transcription.DAL.Models.ChatState", b =>
                {
                    b.HasOne("Transcription.DAL.Models.User", "User")
                        .WithOne("ChatState")
                        .HasForeignKey("Transcription.DAL.Models.ChatState", "ChatStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transcription.DAL.Models.User", b =>
                {
                    b.Navigation("ChatState")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
